# Define reusable config for all Airflow services
x-airflow-common: &airflow-common
  image: airflow-job-postings:latest
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=jobp0sting123
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  volumes:
    - ../airflow/dags:/opt/airflow/dags
    - ../src:/opt/airflow/src
    - ../dbt:/opt/airflow/dbt
    - ../utils:/opt/airflow/utils
  depends_on:
    - postgres
  user: "50000:0"
  env_file:
    - ../.env

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    env_file:
    - ../.env

  airflow-webserver:
    <<: *airflow-common
    build:                               # âœ… build belongs under a service, not in anchor
      context: ..
      dockerfile: airflow/Dockerfile
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 10s
      retries: 5
    env_file:
    - ../.env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./dbt/Job_Postings:/opt/airflow/dbt/Job_Postings

  airflow-scheduler:
    <<: *airflow-common
    build:
      context: ..
      dockerfile: airflow/Dockerfile
    command: scheduler
    restart: always
    env_file:
    - ../.env

  airflow-init:
    <<: *airflow-common
    build:
      context: ..
      dockerfile: airflow/Dockerfile
    entrypoint: /bin/bash
    command: -c "airflow db init && airflow users create \
      --username admin --firstname admin --lastname user --role Admin --email admin@example.com --password admin"
    env_file:
    - ../.env
